### ISSUE TITLE
tests panic when run locally, *sometimes*

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/rust#74]
on a clean `git clone`, running `cargo test` produces:

```
running 6 tests
test commands::print::does_not_fail_with_no_files ... ok
test commands::schema::tests::parse_variant_ref ... ok
test commands::schema::tests::parse_fail ... ok
test commands::schema::tests::parse_hash_ref ... ok
thread panicked while panicking. aborting.
error: test failed, to rerun pass '-p apollo-cli --bin apollo-cli'

Caused by:
  process didn't exit successfully: `/Users/ag_dubs/apollo/rust/target/debug/deps/apollo_cli-d9a8dc7a305f7794` (signal: 4, SIGILL: illegal instruction)
```

**Comment by Enrico2** [comment]
zomg I've been battling this for a while, I can't reproduce locally so I've been iterating on CI .. :(

**Comment by Enrico2** [comment]
I looked into this one a lot over the past couple of days, except I couldn't reproduce it locally. Locally everything passed for me.

I was iterating on CI: https://github.com/apollographql/rust/actions?query=branch%3Aran%2Fworkflow_revamp++

The backtrace and error were showing that we're getting a _timeout_ from the Wiremock MockServer. I asked for some help here: https://github.com/LukeMathWalker/wiremock-rs/issues/13

The odd thing is that the most recent merge to `main` passed CI without issue. 

So, combined with the fact that it was passing for me, and passed CI, maybe some kind of crate cache issue was at play here?

Also FWIW, locally for me `cargo clean && cargo test` still pass :/

**Comment by Enrico2** [comment]
Another important piece of information mentioned there, is that swapping out an instance of `reqwest` with `ureq` made the test pass, and fail on something else that uses `reqwest`.

**Comment by Enrico2** [comment]
WE HAVE PROGRESS!

* I had an existing `Cargo.lock`,
* CI doesn't have a Cargo.lock because we don't check it in!
* I renamed my `Cargo.lock` and tests are failing locally!!
* because the last merge to master passed fine, transitive dependency probably changed between then and now. I'll compare my .lock files

**Comment by ashleygwilliams** [comment]
i'm gonna file an issue for checking in Cargo.lock cc @Enrico2

**Comment by Enrico2** [comment]
Currently comparing the good vs bad Cargo.lock and trying to find the change that causes the failure.

**Comment by Enrico2** [comment]
I've made some progress. Turns out it was only reproducible in CI because we didn't check in our Cargo.lock file. I was able to reproduce locally by deleting my local copy of Cargo.lock, tests started failing.

I then compared the passing vs. failing Cargo.lock, and specifically focused on differences that related to this test.

So, here's what I found: While we specifically depend on `async-std = "1.6.1"`, wiremock has that dependency as `version = "1"`, which brings in `1.6.2` (that's what the failing `Cargo.lock` had)

So, in my `Cargo.lock`, I forced `1.6.1`. That change on its own was not enough, I had to also revert `smol` from `0.1.18` to `0.1.11`.

THAT was the thing that enabled tests to pass. PR coming.
