### ISSUE TITLE
discussion of monorepo project organization

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/rust#82]
hey folks! i know that this conversation has happened previously, but per a convo with @jbaxleyiii it seems that a lot of the discussion was not documented. i'd love if we could use this issue to document the reasons for using a monorepo for project organization, as these reasons affect the tradeoffs of other issues that we will run into, and be relevant for those discussions! thanks :)

**Comment by jbaxleyiii** [comment]
Thanks for opening this up @ashleygwilliams. I'll try to fill out my thoughts in something that hopefully comes out coherent 🤣

## History
When I joined Apollo we had one monorepo (Apollo Server) and several single project repositories (Apollo Client, React Apollo, graphql-anywhere, graphql-tag, etc). I maintained the latter group full time as a single employee while another team member maintained Apollo Server and all of its projects which used lerna. Because the projects that I maintained depended on each other, and were used in conjunction, community memebers had a rightfully hard time knowing where to report bugs, open PRs, and even look through code. I had a really hard time managing changes across projects and both the technical and community burden became a problem of scale that outpaced my ability.

When we built out the apollo-tooling project we created it as a monorepo to try and address this problem. Tooling often has to share the most basic core utilities of an ecosystem so that project took on more of both a tooling and basic graphql core kinda vibe. This, however, introduced new problems due to the JS ecosystem. We pretty much had to publish packages to npm if we wanted to use them as depdencencies since js isn't really a compile language. This meant our publishing and distributing story became more and more complex and packages that we never wanted to become public did just that.

## Enter the new CLI
With the new CLI, we new that we wanted it to be in Rust which can be compiled and didn't need to be shipped to a package repository 😊😊😊. However, we also knew that we would need our own custom parser/printer for changes to the GraphQL language, our own LSP, query planner, composition and validation code, etc. All of these will be used by the cli and LSP and runtimes. My initial thinking was the back and forth of multiple repositories would slow us down as we learn the rust tool chain and itterate on the early APIs of the new projects. Once projects become stable, and if they have public API surface areas, then they could be split out into their own repos if we thing they make sense for an end user to come to that project on its own (i.e does it exist outside of the scope of another project. Like does the query planner matter outside of the gateway for 90% of bug reports?) then we move it to its own repo.

Beyond that, I was afraid of us having to redo / share infra work between mulitple projects as we were still learning how to build, test, release, etc rust projects. So setting this up and rolling out changes across > 1 repo felt like added work with no benefit.

## Rust saved monorepos
Monorepos in JS are a nightmare. So much so that we killed the one for Apollo Client that I built and are working to do the same in Apollo Server. They just aren't worth the effort. However, we are still conceptually keeping as many items under one house in those projects just using the node module resolution to achieve the same goals. With the rust toolchain, monorepos actually seem doable again! Binaries and libaries can share itermediate code that doesn't need to ever be published, versions don't need to be kept in hard lock step, and the tool chain is fast! Without this I don't think we could do a monorepo

## Conclusion
For me, the monorepo helps us to get off the ground faster for projects with a lot of interdepdence where we don't know the right "cut points" at the start. They help us long term on maintence where the community lacks clarity on which part is which part when opening issues, and they lower the amount of infra work we have to maintain.

Hope that was somewhat clear @ashleygwilliams!

**Comment by jbaxleyiii** [comment]
One additional note. After a lot of thought I really don't like the name of the repo. The benefit of a single project is it is really clear to people what this project is and it gets us the benefit of marketing which this project name doesn't do. Monorepos can still do this (see apollo-client and apollo-server) but the scope of this one is still too open for me to understand. Is it all tooling, just the cli, editor integrations, all custom graphql stuff, execution, atlas + stargate, etc?

**Comment by ndintenfass** [comment]
I was invited by James to comment.... 

My thoughts are more medium-term than short-term, as my contribution to this discussion is really about the perspective of those outside our walls. If having a monorepo for all of our Rust code gets us down the road faster I wouldn't want to get in the way of that, but I do think the current structure here is problematic in a couple ways as we get into the ecosystem with this code...

"Rust" is a very "inside-out" name -- it's the language we happen to be moving to in 2020, so it feels very novel and distinct from the rest of our code. But it won't be particularly notable in the future, as we get more used to doing Rust. More importantly, the point of Open Source is to give visibility to those from the outside who want to see the source, and to them a big bucket of all of our code that happens to be Rust isn't a particularly useful distinction. If I want to see Apollo's CLI, if I want to see Apollo's stargate, if I want to see Apollo's atlas it is a strange detail to know that's in a bucket called "Rust". We should try to think of the "outside-in" perspective on how a human who wants to engage with us at the code level would think. Their mental model is much more likely to be based on the product they are using rather than the language that product happens to be written in.

We should also confront that while OSS lies at the heart of the company we haven't built a particularly good muscle at encouraging and absorbing contributions - monorepos based on language create a fair amount of cognitive load for anyone trying to understand the shape of our code and how they might engage in improving it. It also overloads Issues, PRs and the other threads of discussion/contribution we should try to foster over time in order to solidify our position as the go-to GQL tooling.

**Comment by Enrico2** [comment]
I'll also try to fill out my thoughts in something that hopefully comes out coherent 🤣 

In the past I've worked both on large monorepos (which is very different from a monolith) and large code bases that use a git repository for each deliverable package. (i.e. a library or a binary)

My mindset when it comes to this preference revolves around a few aspects, I'll touch on them briefly, because otherwise this will be a long essay :)

* Monorepos make managing componentization easier, since it's easier to move code around between dependent modules.
* A single cognitive change that spans multiple packages is done in a single PR. This means we don't frequently push code that is not yet used.
* At our current phase, the borders of the various crates we create is still amorphic; we still don't know exactly what would be under "atlas", "stargate", "graphql-parser", etc. We're planning on absorbing potentially more gateway functionality, we're planning on bridging wasm. While these separation lines are not solid, we'd have tremendous friction to separate all those things. That is not to say that we shouldn't separate them later, when those lines have been proven to be the right way to go.
* I follow a philosophy that a good engineer constantly improves anything along their path that is worth improving. "worth improving" is tied to the effort. In our situation that effort usually means a PR, description, tests, etc. The more one has to do to create a unit of change, the less likely it is to be done, which means people fix less small things, create more debt, etc. We don't want that to be the case, but we're human beings and we have priorities :)
* **Testing**: Most of the crates we're going to create are going to interact with each other in one way or another, being able to test the code against the most recent version of everything (and not the most recent _published_ version) has tremendous value. This is solvable through some hoop jumping, but again creates more iteration speed slowdowns or a more complex set up.
	* (Also, defining CI jobs once is a huge plus)
* **Ownership**: In our case, most if not all of the same people would own all of the Rust code. As an owner, navigating between communications on different repositories, configuring preferences, labels, CI, etc. is overhead that I currently don't see the value of. 

I recognize none of these take into account the open source aspect and comms that @ndintenfass mentioned above, they revolve around the development experience and iteration speed, and not at all about the externalization of the code itself to the community. I believe that we can significantly alleviate those issues with good documentation (#69) and a better repository name that does a better job capturing what this repository is meant to capture. My vote would go for "Constellation", and a good README explaining what that encapsulates.

**Comment by ashleygwilliams** [comment]
thanks so much for weighing in folks, my thoughts below:

- a monorepo creates a "commons" that is shared amongst the projects within this. this can be a super power, or it can be a liability! the super power can be that with a single effort (readme, CI, issue tracker, labels, branch protection), we can provide value to multiple projects- however, that singular value now needs to be fitting for multiple projects and agreed upon by a large set of folks. in order to get this type of commons to work, i think we'll need more shared values and structure around how decisions get made about these spaces. i don't think we are currently in a great spot with this!
- i believe that the value of open source is that we welcome feedback, discussion, and contributions from external contributors. the cognitive overhead of a monorepo is quite a lot, and the shared commons can make the issue tracker overloaded. long term, if we want to grow beyond "source available" i think a monorepo is a very difficult structure without a lot of discipline and guidance from the maintainers. admittedly, i am a good proxy for an external contributor at the moment (being new to apollo), and the current state of the repo is definitely difficult to onboard to.
- lastly, and this is likely my controversial point: going slow is a feature. especially in open source, where external contributors come from different timezones, and have different abilities to keep up and contribute, a small amount of overhead allows a larger number of people to keep up. long term, i actually think that going slow, so that more people can keep up, actually makes a project's overall velocity much faster, though it is true that it slows an individual contributor down. i feel this is actually a good strategy in both open source and not open source, though the conditions of open source make it more obvious. 

anyways, i hear the arguments about velocity and unsure abstraction boundaries, and i could imagine that the monorepo structure can help us get there fo the short term... but i think we should have a sense of what the conditions are for when we will solidify those boundaries and split the repositories. we will need to have those boundaries become a contract for end users *anyways* and so also giving a sense of when the apis are stable and ready for public consumption would be good.

i am worried that starting in the monorepo where we can fluidly move between projects will be a privilege that is hard to give up. there is something to be said about developing the discipline of a multiple repo structure earlier on, and if it something we intend to do long term, we should be careful to not put it off.

**Comment by ashleygwilliams** [comment]
closing as we've opted to move the CLI to it's own repo
