### ISSUE TITLE
move CDN into CLI dir

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/rust#96]
in writing the README (#69/#95) i've realized that `cdn` is not really a standalone project in this monorepo, but really a sub project of the CLI. we should move it into that dir to reflect that. what do folks think?

**Comment by abernix** [comment]
I like this.  I _believe_ that there is some auto-deployment of that code happening via a GitHub Action (to Cloudflare) that might need to be adjusted, but otherwise seems like a better tiered structure of concerns to me (due to the CDN being the component that is responsible for the installation/distribution of the CLI)

**Comment by Enrico2** [comment]
There are a few questions this brings to mind. These are all just my _opinions_ (instead of writing IMO everywhere.)

First, around folder organization: Do we want folders to represent a project hierarchy, or do we want them to represent a deliverable package or a combination of both?

A project oriented hierarchy _might_ look something like
```
|- cli
  |- cdn
    |- src
    |- package.json
    |- ...
  |- ap
    |- src
    |- Cargo.toml
    |- ...
|- gateway
  |- query-planner
  |- atlas
  |- ...
```

The advantages here are that each piece of code is naturally categorized in the project it belongs to. It makes it easier to track changes to anything that has to do with a specific project to all changes under one folder.
This structure works well in monorepos that are (1) contributed to by many many teams and (2) do not overlap that much.

One of the main advantages of a monorepo is often the easy access to common code, and with a structure like this, one usually ends up with
```
|- common # contributed to by everyone
|- cli # contributed to by CLI folks
  |- cdn
  |- ap
|- gateway # contributed to by gateway folks
  |- ...
```

Alternative, a monorepo oriented by units of "release" would have a folder for each "package"/"deployable"/"binary" -- for a lack of a better term, we can call these _packages_.

That's kind of what we have now. This is mostly because we are using Rust's workspace organization as the root of the rust repo, so each rust crate has a root folder, and with the current state of things, I think it'd be awkward to put a completely separate _package_ (cdn) inside the cli _crate_ folder.

But that got me thinking: 
1. Does the CDN even belong in this repository?
1. Should the `cli` create be separate from the rust workspace as an independent crate? We have some plans about other crates and they're more around stuff for the gateway/constellation, so maybe the CLI should just be a separate repo (with the CDN) all together? 

At the end of it, I think we should decide to tackle these questions further down the line, when we add more packages to the repo, and see how these interact.
It's good to create an issue, to remind ourselves to address it, as a TOOD item, but I don't feel there's any urgency around it. (Also some other PRs assume the current paths are in flight, it'd be easier to change these things separately)

Also some of these thoughts might be more appropriate in #82 ?
I think I had previously read that one as "to MR or not MR?", but really Rust workspaces are useful and ergonomic, so some kind of grouping of crates in the same repo makes sense, but that doesn't mean all of our Rust should be in the same repo.

**Comment by ashleygwilliams** [comment]
closing as we've opted to move the CLI and it's installer to it's own repo
